### ISSUE TITLE
Cannot use @sass-collective/breakpoint due to ~ specifier

### ISSUE THREAD

**Issue by aminya** [sass-collective/sass-collective#17]
I cannot use @sass-collective/breakpoint, because it imports the libraries using `~`. This is not supported by Sass or other bundlers. It is only a Webpack thing, which makes these libraries non-portable.

```sass
To @import files from node_modules, use "@sass-collective/strip-unit"
  ╷
6 │ @use "~@sass-collective/strip-unit";
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

@sass-collective\breakpoint\\_functions.scss 6:1 
```

**Comment by borisdamevin** [comment]
@aminya Thank for the fix!

**Comment by aminya** [comment]
You're welcome
